Added good looking UI with light/dark theme
t3dotgg/quickpic pull request #11
Opened 2024-11-10 04:14 UTC by TheJagStudio

This pull request introduces several enhancements and bug fixes to the `tools` section of the application. The most significant changes include the addition of a theme toggle button, drag-and-drop functionality for image upload, and various UI improvements.

### New Features:
* Added a theme toggle button to the `ToolsLayout` component, allowing users to switch between light and dark modes. (`src/app/(tools)/layout.tsx`)
* Implemented drag-and-drop functionality for image upload in the `RoundedTool` and `SquareTool` components. (`src/app/(tools)/rounded-border/rounded-tool.tsx`, `src/app/(tools)/square-image/square-tool.tsx`) [[1]](diffhunk://#diff-65569373b1a8356530ea0452720a0a6362256beb9531d750080cda18c09a63bcL188-R270) [[2]](diffhunk://#diff-e706856ca6b4b5f946a264085778f06889eaf5648115fa1fe149f5fe901ffa14L40-R72)

### UI Improvements:
* Updated the `SaveAsPngButton` and other buttons to use gradient backgrounds for a more modern look. (`src/app/(tools)/rounded-border/rounded-tool.tsx`)
* Enhanced the `ImageRenderer` component to better handle image scaling and display. (`src/app/(tools)/rounded-border/rounded-tool.tsx`)
* Increased the preview canvas size in the `SquareTool` component for a clearer image preview. (`src/app/(tools)/square-image/square-tool.tsx`)

2024-11-10 05:17 UTC, Bashamega requested changes

2024-11-10 05:17 UTC, Bashamega commented on pnpm-lock.yaml
Please do not remove this file.

2024-11-10 05:17 UTC, Bashamega commented on package-lock.json
No need for this :)

2024-11-11 06:13 UTC, t3dotgg commented
I quite like the horizontal layout on the upload pages. If you're down to redo these changes without breaking the package files I'm down to reconsider 🙏 open a fresh PR if you reroll this

2024-11-11 06:13 UTC, closed without merging